---
title: "individual2"
author: "Jian Kai Lee;jiankailee"
date: "3/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Part 1

```{r }
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyverse)
defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offensive <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
biography <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
#str(defense)
#str(offensive)

defense <-defense %>% rename(Opponent=Opponent_Opponent) %>% mutate(Opponent=factor(Opponent))
defense <-defense %>% mutate(Name=factor(Name))
lvls <- as.character(sort(unique(defense$Opponent)))
lvls <- c('UNI', lvls[lvls != 'UNI'])
defense <- defense %>% mutate(Opponent = factor(Opponent, lvls))

defense <- defense%>%mutate_at(c("Tackles_Solo","Tackles_ASST","Tackles_TFL","Tackles_Sack","Turnover_FF","Turnover_FR","Turnover_INT","Pass_QBH","Pass_PB"),as.numeric)
#str(defense)

offensive <-offensive %>% rename(Opponent=Opponent_Opponent) %>% mutate(Opponent=factor(Opponent))
offensive <-offensive %>% mutate(Name=factor(Name))
lvls <- as.character(sort(unique(offensive$Opponent)))
lvls <- c('UNI', lvls[lvls != 'UNI'])
offensive <- offensive %>% mutate(Opponent = factor(Opponent, lvls))

offensive <- offensive %>%mutate_if(is.character,as.numeric,na.rm=TRUE)
#str(offensive)

biography <-biography %>% mutate(Name=factor(Name))
biography <- biography %>% mutate_at(c("Weight"),as.numeric)
height1 <-strsplit(biography$Height,"-")
biography$Height <-str_replace_all(biography$Height,'-','.')
biography<-biography%>% mutate(Height=as.numeric(Height)* 0.3048) 
#str(biography)

defClean <-defense
offClean <- offensive
bioClean <- biography

str(defClean)
str(offClean)
str(bioClean)
```

Part 2
```{r}

```

