---
title: "team"
author: "Jian Kai Lee;jiankailee"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Part 1
```{r }
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyverse)

defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offensive <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
biography <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')

#rename opponent and mutate to factor
defense <-defense %>% rename(Opponent=Opponent_Opponent) %>% mutate(Opponent=factor(Opponent))

#mutate name to factor
defense <-defense %>% mutate(Name=factor(Name))

#order opponent column in a meaninnful fashion: factor and make 'UNI' the first level
lvls <- as.character(sort(unique(defense$Opponent)))
lvls <- c('UNI', lvls[lvls != 'UNI'])
defense <- defense %>% mutate(Opponent = factor(Opponent, lvls))

#mutate stat from chr to num
defense <- defense%>%mutate_at(c("Tackles_Solo","Tackles_ASST","Tackles_TFL","Tackles_Sack","Turnover_FF","Turnover_FR","Turnover_INT","Pass_QBH","Pass_PB"),as.numeric)



#rename opponent and mutate to factor
offensive <-offensive %>% rename(Opponent=Opponent_Opponent) %>% mutate(Opponent=factor(Opponent))

#mutate name to factor
offensive <-offensive %>% mutate(Name=factor(Name))

#order opponent column in a meaninnful fashion: factor and make 'UNI' the first level
lvls <- as.character(sort(unique(offensive$Opponent)))
lvls <- c('UNI', lvls[lvls != 'UNI'])
offensive <- offensive %>% mutate(Opponent = factor(Opponent, lvls))

#mutate stat from chr to num
offensive <- offensive %>%mutate_if(is.character,as.numeric,na.rm=TRUE)


#rename opponent and mutate to factor
biography <-biography %>% mutate(Name=factor(Name))

#mutate weight to num
biography <- biography %>% mutate_at(c("Weight"),as.numeric)

#mutate height to centimeter from chr
biography$Height <-str_replace_all(biography$Height,'-','.')
biography<-biography%>% mutate(Height=as.numeric(Height)* 30.48) 

defClean <-defense
offClean <- offensive
bioClean <- biography

str(defClean)
str(offClean)
str(bioClean)
```

part 2
```{r}

```
